// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bi3c25tXsirTmyq-MOIhgO1L5XxRTHs',
    appId: '1:268663350911:android:d84cfcc42f6b4b9a66014a',
    messagingSenderId: '268663350911',
    projectId: 'plombipro-devlpt',
    storageBucket: 'plombipro-devlpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2OYonbLtq4Nkn5izsq78isPQwE7dw5Go',
    appId: '1:268663350911:ios:93817ef0f50de33b66014a',
    messagingSenderId: '268663350911',
    projectId: 'plombipro-devlpt',
    storageBucket: 'plombipro-devlpt.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwTgy76QzYeZ3SCYfcLBn9RQFmL123I-w',
    appId: '1:268663350911:web:3508642b8e87efcd66014a',
    messagingSenderId: '268663350911',
    projectId: 'plombipro-devlpt',
    authDomain: 'plombipro-devlpt.firebaseapp.com',
    storageBucket: 'plombipro-devlpt.firebasestorage.app',
    measurementId: 'G-53V5X7L6RM',
  );

}